name: CI
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 20
          packageManager: pnpm
          workingDirectory: ./
          packageManagerVersion: 8

      - run: pnpm install

      # Verify it compiles
      - run: pnpm build
